// <auto-generated />
using System;
using DevolucionesGarantias.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DevolucionesGarantias.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DevolucionesGarantias.Domain.Entities.ArchivoExportado", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Archivo")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("file");

                    b.Property<DateTimeOffset>("ExportedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("exported_at");

                    b.Property<string>("ExportedBy")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("exported_by");

                    b.Property<string>("Formato")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("format");

                    b.Property<string>("NombreArchivo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("file_name");

                    b.Property<Guid>("ReporteId")
                        .HasColumnType("uuid")
                        .HasColumnName("report_id");

                    b.HasKey("Id");

                    b.HasIndex("ReporteId")
                        .HasDatabaseName("ix_exported_files_report_id");

                    b.ToTable("exported_files", (string)null);
                });

            modelBuilder.Entity("DevolucionesGarantias.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("action");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("entity_name");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("ip_address");

                    b.Property<string>("NewValues")
                        .HasColumnType("jsonb")
                        .HasColumnName("new_values");

                    b.Property<string>("OldValues")
                        .HasColumnType("jsonb")
                        .HasColumnName("old_values");

                    b.Property<string>("TraceId")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("trace_id");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("user_agent");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_audit_logs_created_at");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_audit_logs_user_id");

                    b.HasIndex("EntityName", "EntityId")
                        .HasDatabaseName("ix_audit_logs_entity");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("DevolucionesGarantias.Domain.Entities.CasoAsignado", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AssignedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assigned_at");

                    b.Property<string>("AssignedBy")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("assigned_by");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("status");

                    b.Property<Guid>("ProveedorId")
                        .HasColumnType("uuid")
                        .HasColumnName("provider_id");

                    b.Property<Guid>("SolicitudId")
                        .HasColumnType("uuid")
                        .HasColumnName("request_id");

                    b.HasKey("Id");

                    b.HasIndex("ProveedorId")
                        .HasDatabaseName("ix_assigned_cases_provider_id");

                    b.HasIndex("SolicitudId")
                        .HasDatabaseName("ix_assigned_cases_request_id");

                    b.ToTable("assigned_cases", (string)null);
                });

            modelBuilder.Entity("DevolucionesGarantias.Domain.Entities.ComentarioInterno", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Autor")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("author");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("SolicitudId")
                        .HasColumnType("uuid")
                        .HasColumnName("request_id");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("text");

                    b.Property<bool>("VisibleToCustomer")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("visible_to_customer");

                    b.HasKey("Id");

                    b.HasIndex("SolicitudId")
                        .HasDatabaseName("ix_internal_comments_request_id");

                    b.ToTable("internal_comments", (string)null);
                });

            modelBuilder.Entity("DevolucionesGarantias.Domain.Entities.DecisionOperativa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Approved")
                        .HasColumnType("boolean")
                        .HasColumnName("approved");

                    b.Property<DateTimeOffset>("DecidedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("decided_at");

                    b.Property<string>("DecidedBy")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("decided_by");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("reason");

                    b.Property<Guid>("SolicitudId")
                        .HasColumnType("uuid")
                        .HasColumnName("request_id");

                    b.HasKey("Id");

                    b.HasIndex("SolicitudId")
                        .HasDatabaseName("ix_operational_decisions_request_id");

                    b.ToTable("operational_decisions", null, t =>
                        {
                            t.HasCheckConstraint("ck_operational_decisions_reason_not_empty", "length(trim(reason)) > 0");
                        });
                });

            modelBuilder.Entity("DevolucionesGarantias.Domain.Entities.DictamenTecnico", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("IssuedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("issued_at");

                    b.Property<string>("IssuedBy")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("issued_by");

                    b.Property<string>("MotivoTecnico")
                        .IsRequired()
                        .HasMaxLength(1500)
                        .HasColumnType("character varying(1500)")
                        .HasColumnName("technical_reason");

                    b.Property<string>("Observaciones")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("observations");

                    b.Property<string>("Resultado")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("result");

                    b.Property<Guid>("SolicitudId")
                        .HasColumnType("uuid")
                        .HasColumnName("request_id");

                    b.HasKey("Id");

                    b.HasIndex("SolicitudId")
                        .IsUnique()
                        .HasDatabaseName("ux_technical_rulings_request_id");

                    b.ToTable("technical_rulings", null, t =>
                        {
                            t.HasCheckConstraint("ck_technical_rulings_no_procede_reason", "result <> 'NoProcede' OR length(trim(technical_reason)) > 0");
                        });
                });

            modelBuilder.Entity("DevolucionesGarantias.Domain.Entities.Evidencia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Archivo")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("file");

                    b.Property<string>("NombreArchivo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("file_name");

                    b.Property<long>("SizeInBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_in_bytes");

                    b.Property<Guid>("SolicitudId")
                        .HasColumnType("uuid")
                        .HasColumnName("request_id");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UploadedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("uploaded_at");

                    b.Property<string>("UploadedBy")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("uploaded_by");

                    b.HasKey("Id");

                    b.HasIndex("SolicitudId")
                        .HasDatabaseName("ix_evidence_request_id");

                    b.ToTable("evidence", null, t =>
                        {
                            t.HasCheckConstraint("ck_evidence_size_non_negative", "size_in_bytes >= 0");
                        });
                });

            modelBuilder.Entity("DevolucionesGarantias.Domain.Entities.IndicadorMetrica", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<Guid>("ReporteId")
                        .HasColumnType("uuid")
                        .HasColumnName("report_id");

                    b.Property<string>("Unidad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("unit");

                    b.Property<decimal>("Valor")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.HasIndex("ReporteId")
                        .HasDatabaseName("ix_metric_indicators_report_id");

                    b.ToTable("metric_indicators", (string)null);
                });

            modelBuilder.Entity("DevolucionesGarantias.Domain.Entities.LoginAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("email");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("failure_reason");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("ip_address");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<bool>("Succeeded")
                        .HasColumnType("boolean")
                        .HasColumnName("succeeded");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("user_agent");

                    b.HasKey("Id");

                    b.HasIndex("Correo")
                        .HasDatabaseName("ix_login_attempts_email");

                    b.ToTable("login_attempts", (string)null);
                });

            modelBuilder.Entity("DevolucionesGarantias.Domain.Entities.Pedido", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<DateTimeOffset>("FechaCompra")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("purchase_date");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("number");

                    b.Property<string>("Total")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("total");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId")
                        .HasDatabaseName("ix_orders_customer_id");

                    b.HasIndex("Numero")
                        .IsUnique()
                        .HasDatabaseName("ux_orders_number");

                    b.ToTable("orders", (string)null);
                });

            modelBuilder.Entity("DevolucionesGarantias.Domain.Entities.Producto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<DateTimeOffset>("FechaCompra")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("purchase_date");

                    b.Property<DateTimeOffset>("GarantiaHasta")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("warranty_until");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)")
                        .HasColumnName("name");

                    b.Property<Guid>("PedidoId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<string>("PrecioUnitario")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("unit_price");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("sku");

                    b.HasKey("Id");

                    b.HasIndex("PedidoId")
                        .HasDatabaseName("ix_products_order_id");

                    b.HasIndex("Sku")
                        .HasDatabaseName("ix_products_sku");

                    b.ToTable("products", null, t =>
                        {
                            t.HasCheckConstraint("ck_products_quantity_positive", "quantity > 0");
                        });
                });

            modelBuilder.Entity("DevolucionesGarantias.Domain.Entities.RecepcionProducto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CostoEnvio")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("shipping_cost");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("address");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at");

                    b.Property<string>("ReceivedBy")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("received_by");

                    b.Property<Guid>("SolicitudId")
                        .HasColumnType("uuid")
                        .HasColumnName("request_id");

                    b.HasKey("Id");

                    b.HasIndex("SolicitudId")
                        .IsUnique()
                        .HasDatabaseName("ux_product_receptions_request_id");

                    b.ToTable("product_receptions", (string)null);
                });

            modelBuilder.Entity("DevolucionesGarantias.Domain.Entities.Reporte", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Filtro")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("filter_json");

                    b.Property<DateTimeOffset>("GeneratedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("generated_at");

                    b.Property<string>("GeneratedBy")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("generated_by_user_id");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("GeneratedAt")
                        .HasDatabaseName("ix_reports_generated_at");

                    b.HasIndex("GeneratedBy")
                        .HasDatabaseName("ix_reports_generated_by_user_id");

                    b.ToTable("reports", (string)null);
                });

            modelBuilder.Entity("DevolucionesGarantias.Domain.Entities.RequestTimeline", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("created_by");

                    b.Property<string>("EstadoAnterior")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("previous_status");

                    b.Property<string>("EstadoNuevo")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("new_status");

                    b.Property<string>("Evento")
                        .IsRequired()
                        .HasMaxLength(600)
                        .HasColumnType("character varying(600)")
                        .HasColumnName("event");

                    b.Property<Guid>("SolicitudId")
                        .HasColumnType("uuid")
                        .HasColumnName("request_id");

                    b.HasKey("Id");

                    b.HasIndex("SolicitudId")
                        .HasDatabaseName("ix_request_timeline_request_id");

                    b.ToTable("request_timeline", (string)null);
                });

            modelBuilder.Entity("DevolucionesGarantias.Domain.Entities.Rol", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("name");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique()
                        .HasDatabaseName("ux_roles_name");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("DevolucionesGarantias.Domain.Entities.Sesion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("token");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("ix_sessions_user_id");

                    b.ToTable("sessions", (string)null);
                });

            modelBuilder.Entity("DevolucionesGarantias.Domain.Entities.Solicitud", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("created_by");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<string>("EstadoActual")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("status");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reason");

                    b.Property<Guid>("PedidoId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<string>("PreferenciaSolucion")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("solution_preference");

                    b.Property<Guid>("ProductoId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId")
                        .HasDatabaseName("ix_requests_customer_id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_requests_created_at");

                    b.HasIndex("EstadoActual")
                        .HasDatabaseName("ix_requests_status");

                    b.HasIndex("PedidoId")
                        .HasDatabaseName("ix_requests_order_id");

                    b.HasIndex("ProductoId")
                        .HasDatabaseName("ix_requests_product_id");

                    b.HasIndex("Tipo")
                        .HasDatabaseName("ix_requests_type");

                    b.HasIndex("ClienteId", "PedidoId", "ProductoId", "Tipo", "Motivo")
                        .IsUnique()
                        .HasDatabaseName("ux_requests_duplicate_guard");

                    b.ToTable("requests", null, t =>
                        {
                            t.HasCheckConstraint("ck_requests_quantity_positive", "quantity > 0");

                            t.HasCheckConstraint("ck_requests_reason_not_empty", "length(trim(reason)) > 0");
                        });
                });

            modelBuilder.Entity("DevolucionesGarantias.Domain.Entities.SolicitudInformacionAdicional", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("Deadline")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deadline");

                    b.Property<bool>("IsResolved")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_resolved");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasMaxLength(1500)
                        .HasColumnType("character varying(1500)")
                        .HasColumnName("message");

                    b.Property<DateTimeOffset>("RequestedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("requested_at");

                    b.Property<string>("RequestedBy")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("requested_by");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.Property<string>("Response")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("response");

                    b.Property<Guid>("SolicitudId")
                        .HasColumnType("uuid")
                        .HasColumnName("request_id");

                    b.HasKey("Id");

                    b.HasIndex("SolicitudId")
                        .HasDatabaseName("ix_additional_information_requests_request_id");

                    b.ToTable("additional_information_requests", (string)null);
                });

            modelBuilder.Entity("DevolucionesGarantias.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("email");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("created_by");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("password_hash");

                    b.Property<DateTimeOffset?>("UltimoAcceso")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_access_at");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("updated_by");

                    b.Property<string>("user_type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("user_type");

                    b.HasKey("Id");

                    b.HasIndex("Correo")
                        .IsUnique()
                        .HasDatabaseName("ux_users_email");

                    b.ToTable("users", (string)null);

                    b.HasDiscriminator<string>("user_type").HasValue("Usuario");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("DevolucionesGarantias.Domain.Entities.ValidacionGarantia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsWarrantyValid")
                        .HasColumnType("boolean")
                        .HasColumnName("is_warranty_valid");

                    b.Property<Guid>("ProductoId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<string>("Reason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("reason");

                    b.Property<Guid>("SolicitudId")
                        .HasColumnType("uuid")
                        .HasColumnName("request_id");

                    b.Property<DateTimeOffset>("ValidatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("validated_at");

                    b.Property<string>("ValidatedBy")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("validated_by");

                    b.HasKey("Id");

                    b.HasIndex("ProductoId")
                        .HasDatabaseName("ix_warranty_validations_product_id");

                    b.HasIndex("SolicitudId")
                        .IsUnique()
                        .HasDatabaseName("ux_warranty_validations_request_id");

                    b.ToTable("warranty_validations", (string)null);
                });

            modelBuilder.Entity("user_roles", b =>
                {
                    b.Property<Guid>("user_id")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("role_id")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("user_id", "role_id");

                    b.HasIndex("role_id")
                        .HasDatabaseName("ix_user_roles_role_id");

                    b.ToTable("user_roles", (string)null);
                });

            modelBuilder.Entity("DevolucionesGarantias.Domain.Entities.Administrador", b =>
                {
                    b.HasBaseType("DevolucionesGarantias.Domain.Entities.Usuario");

                    b.HasDiscriminator().HasValue("administrador");
                });

            modelBuilder.Entity("DevolucionesGarantias.Domain.Entities.Cliente", b =>
                {
                    b.HasBaseType("DevolucionesGarantias.Domain.Entities.Usuario");

                    b.HasDiscriminator().HasValue("cliente");
                });

            modelBuilder.Entity("DevolucionesGarantias.Domain.Entities.Proveedor", b =>
                {
                    b.HasBaseType("DevolucionesGarantias.Domain.Entities.Usuario");

                    b.HasDiscriminator().HasValue("proveedor");
                });

            modelBuilder.Entity("DevolucionesGarantias.Domain.Entities.ArchivoExportado", b =>
                {
                    b.HasOne("DevolucionesGarantias.Domain.Entities.Reporte", null)
                        .WithMany("Archivos")
                        .HasForeignKey("ReporteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DevolucionesGarantias.Domain.Entities.AuditLog", b =>
                {
                    b.HasOne("DevolucionesGarantias.Domain.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("DevolucionesGarantias.Domain.Entities.CasoAsignado", b =>
                {
                    b.HasOne("DevolucionesGarantias.Domain.Entities.Proveedor", null)
                        .WithMany()
                        .HasForeignKey("ProveedorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DevolucionesGarantias.Domain.Entities.Solicitud", null)
                        .WithMany()
                        .HasForeignKey("SolicitudId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DevolucionesGarantias.Domain.Entities.ComentarioInterno", b =>
                {
                    b.HasOne("DevolucionesGarantias.Domain.Entities.Solicitud", null)
                        .WithMany()
                        .HasForeignKey("SolicitudId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DevolucionesGarantias.Domain.Entities.DecisionOperativa", b =>
                {
                    b.HasOne("DevolucionesGarantias.Domain.Entities.Solicitud", null)
                        .WithMany()
                        .HasForeignKey("SolicitudId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DevolucionesGarantias.Domain.Entities.DictamenTecnico", b =>
                {
                    b.HasOne("DevolucionesGarantias.Domain.Entities.Solicitud", null)
                        .WithOne()
                        .HasForeignKey("DevolucionesGarantias.Domain.Entities.DictamenTecnico", "SolicitudId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DevolucionesGarantias.Domain.Entities.Evidencia", b =>
                {
                    b.HasOne("DevolucionesGarantias.Domain.Entities.Solicitud", null)
                        .WithMany("Evidencias")
                        .HasForeignKey("SolicitudId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DevolucionesGarantias.Domain.Entities.IndicadorMetrica", b =>
                {
                    b.HasOne("DevolucionesGarantias.Domain.Entities.Reporte", null)
                        .WithMany("Metricas")
                        .HasForeignKey("ReporteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DevolucionesGarantias.Domain.Entities.Pedido", b =>
                {
                    b.HasOne("DevolucionesGarantias.Domain.Entities.Cliente", null)
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("DevolucionesGarantias.Domain.Entities.Producto", b =>
                {
                    b.HasOne("DevolucionesGarantias.Domain.Entities.Pedido", null)
                        .WithMany("Productos")
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DevolucionesGarantias.Domain.Entities.RecepcionProducto", b =>
                {
                    b.HasOne("DevolucionesGarantias.Domain.Entities.Solicitud", null)
                        .WithOne()
                        .HasForeignKey("DevolucionesGarantias.Domain.Entities.RecepcionProducto", "SolicitudId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DevolucionesGarantias.Domain.Entities.RequestTimeline", b =>
                {
                    b.HasOne("DevolucionesGarantias.Domain.Entities.Solicitud", null)
                        .WithMany("Timeline")
                        .HasForeignKey("SolicitudId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DevolucionesGarantias.Domain.Entities.Sesion", b =>
                {
                    b.HasOne("DevolucionesGarantias.Domain.Entities.Usuario", null)
                        .WithMany("Sesiones")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DevolucionesGarantias.Domain.Entities.Solicitud", b =>
                {
                    b.HasOne("DevolucionesGarantias.Domain.Entities.Cliente", null)
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DevolucionesGarantias.Domain.Entities.Pedido", null)
                        .WithMany()
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DevolucionesGarantias.Domain.Entities.Producto", null)
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("DevolucionesGarantias.Domain.Entities.SolicitudInformacionAdicional", b =>
                {
                    b.HasOne("DevolucionesGarantias.Domain.Entities.Solicitud", null)
                        .WithMany()
                        .HasForeignKey("SolicitudId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DevolucionesGarantias.Domain.Entities.ValidacionGarantia", b =>
                {
                    b.HasOne("DevolucionesGarantias.Domain.Entities.Producto", null)
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DevolucionesGarantias.Domain.Entities.Solicitud", null)
                        .WithOne()
                        .HasForeignKey("DevolucionesGarantias.Domain.Entities.ValidacionGarantia", "SolicitudId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("user_roles", b =>
                {
                    b.HasOne("DevolucionesGarantias.Domain.Entities.Rol", null)
                        .WithMany()
                        .HasForeignKey("role_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DevolucionesGarantias.Domain.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DevolucionesGarantias.Domain.Entities.Pedido", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("DevolucionesGarantias.Domain.Entities.Reporte", b =>
                {
                    b.Navigation("Archivos");

                    b.Navigation("Metricas");
                });

            modelBuilder.Entity("DevolucionesGarantias.Domain.Entities.Solicitud", b =>
                {
                    b.Navigation("Evidencias");

                    b.Navigation("Timeline");
                });

            modelBuilder.Entity("DevolucionesGarantias.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("Sesiones");
                });
#pragma warning restore 612, 618
        }
    }
}
